name: WIZZY Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false 

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows
        run: flutter config --enable-windows-desktop

      # --- L'ÉTAPE MAGIQUE : ON FORCE LA VERSION 3.5 DANS LES FICHIERS DE PLUGINS ---
      - name: Patch Firebase CMake
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path . -Filter "CMakeLists.txt" -Recurse
          foreach ($file in $files) {
              $content = Get-Content $file.FullName
              $content = $content -replace 'cmake_minimum_required\(VERSION 3\.0\)', 'cmake_minimum_required(VERSION 3.5)'
              $content = $content -replace 'cmake_minimum_required\(VERSION 3\.1\)', 'cmake_minimum_required(VERSION 3.5)'
              Set-Content $file.FullName $content
          }

      - name: Build Windows Exe
        # On utilise la commande la plus simple possible sans tirets bizarres
        run: flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wizzy-windows-release
          path: build/windows/x64/runner/Release/
